### ISSUE TITLE
investigate inconsistent application of top padding for embedded iframes

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2022]
http://www.dreamwidth.org/support/see_request?id=35889

The reported behavior seems to be related to something named `$padding_based_on_aspect_ratio` in LJ/EmbedModule.pm.  The person reporting the issue says the padding is undesired, but the larger question is, why is it only manifesting in preview?  Did we change the behavior of the code at some point, but fail to update it in all views?  Under what circumstances might this extra padding be desired?

(The user's journal style, in which the embed is appearing "correctly", is Practicality - in case that is relevant to the investigation.)

**Comment by kareila** [comment]
Investigating further, the padding is applied in both regular view and preview, but it only looks incorrect in preview.  And I've figured out why: it's because the preview window doesn't include the styling from htdocs/stc/lj_base.css, which contains the following block:
```css
.lj_embedcontent-ratio {
    position: relative;
    height: 0;
    /* this technique requires a padding top, but we calculate that dynamically and put it inline */
}
```
Including this stylesheet in preview/entry.bml should fix the problem.
