### ISSUE TITLE
"Less-quick reply" form blows out the layout on mobile

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2410]
Quick-reply forms are built by [quickreply.tt](https://github.com/dreamwidth/dw-free/blob/develop/views/journal/quickreply.tt), and for whatever historical reason, there's two versions available: 

- "quicker reply," added in #1078, which is used on multi-entry pages ("reading" and "recent"). This is fine.
- "less-quick reply," which is used on single-entry pages. This is pretty bad! It's a big `<table>`, and it always overflows and trashes the page layout on mobile. It's even wide enough that it's hard to type in, because of the way iOS Safari handles textarea focus. 

<a href='https://roadrunnertwice.dreamwidth.org/file/9961.png'><img src='https://roadrunnertwice.dreamwidth.org/file/320x320/9961.png' alt='' title='quick reply blowout'/></a>

First question: Can I just refactor the markup in quickreply.tt (and wherever the CSS for that comes from) and lay it out more like the quicker reply? Or is there some hidden requirement that would make that a no-go?

Second question: If the markup does have to stay put, is there some way I can add some CSS on top of every layout except the specifically problematic ones? 

Here's how I fixed this in my own journal style:

```css
#qrform > table,
#qrform > table > tbody {
    /* "the de-table-izing ray! I can dodge this!" */
    display: block;
    /* NARRATOR: but he couldn't. */
}

#qrform > table tr {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
}

#qrform > table td {
    /* dissolve <td> elements, treat their children as direct children of <tr>s */
    display: contents;
}

#qrform > table #subject {
    max-width: 90%;
}

#qrform > table tr > td > * {
    margin-top: .3rem;
}

/* tweak for misaligned quote button */
#qrform > table span#quotebuttonspan {
    display: contents;
}
#qrform > table span#quotebuttonspan > input {
    margin-top: .3rem;
}

#qrform > table textarea#body {
    margin-bottom: .3rem; /* extra room before "post comment" */
}
```

<a href='https://roadrunnertwice.dreamwidth.org/file/10492.png'><img src='https://roadrunnertwice.dreamwidth.org/file/320x320/10492.png' alt='' title='corners quick reply fix firefox'/></a>
