### ISSUE TITLE
Icon browser / `iconselector` pop-up is useless on mobile

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2411]
The "new-new" icon browser (first appeared on beta new entry page) is superior to the "old-new" one, so we should use it on journal pages. 

This requires making Foundation components available in S2 pages (which I've already done), and it'll be gated behind the same beta as the site-scheme comment pages refresh. 

Miscellaneous to-dos:

- [x] there are like four different ways to get the list of icons, and also the new entry page uses a different approach for the random icon and update-the-preview-icon functions. Can we standardize all this? (It looks like the icon list in the template doesn’t matter for the browser maybe? Like it’s getting its data via xhr from somewhere.)
- [x] Gotta wire the existing controls up correctly. 
- [x] Gotta clean up some of the foundationizing stuff where I was sloppy because I didn’t know if it was even gonna work. 
- [x] Get approval for the general approach of bringing foundation components into journal S2 land. 
- [x] Figure out what was going on with need_res getting ignored in .tt templates, but only under certain conditions. 
- [x] Clean up resource groups shenanigans in general. 
- [x] When ther're multiple keywords, you're supposed to style the currently selected one in the browser. Most s2 styles don't have anything for that; gotta figure out a way to do a fallback for it. 
- [x] Selected icon should be styled with a highlight-y border, but s2 styles don't have an affordance for that. And picking an arbitrary one will look bad with many styles. 
- [x] Something I did to fix that breakage in the modal slide animation might have caused the page to jump to the top when it first does its zwoop-zwoop thingie sometimes. Wonder wtf's up with that. Need reliable repro; only happens rarely. 
- [x] Enable new-new browser in talkform, since the jquery one's disabled now if you're in the beta. 
- [x] existing issue: keywords look bad if they wrap. 
- [x] “select” button too small and out of the way. (Less of an issue if there's alternate ways to finalize on mobile.)
- [x] no double-click finalize on mobile. (Less of an issue if select button is easier to get to.)
- [x] on mobile, if you scroll a mile to find your icon, you're way far away from the comment form when you finish and close it. Should be able to bounce back to home? 
- [x] foundation "block grid" is a crap replacement for flexbox. huck it. 
- [x] Figure out how to style it on journal style pages. (oh heck yeah, just shim into the thing core2 does for contextual popups!) 
- [x] Make second-click-confirms more discoverable. (I'm just putting a note at the top, screw it.)
- [ ] (optional) Come up with a way to switch between upload order and keyword order in the browser, like the option on icons pages. Doing this splits keywords for icons with multiple keywords, so they display multiple times. 
- [x] Actually I changed my mind, this should probably use CSS grid with auto-layout instead of flexbox (with a fallback for browsers that suck). It's weird that things kind of slide over into the empty space if it's not on a full line; weird enough that early testers noticed it. 
- [x] If you're scrolled way rightwards into indented comment space, the modal positions itself against the left edge of the _page,_ instead of the _viewport_ like it ought to. So you gotta go hunting for it. Esp. fugly on mobile. s/o to alexseanchai for catching that one. 
- [x] Reconsider the way small icons with metatext are laid out? IDK about it. At least one tester was surprised by it. Might be nothing for it tho.
- [x] My refactor of the thing that builds the icon keyword dropdown (which is before the browser even comes into the picture) broke selecting icons with no keywords. Do we care?

-----

## Old description

Selecting icons visually is nice, and I'd like to be able to do it on mobile too. But:

<img src="https://user-images.githubusercontent.com/484309/54964753-dc044980-4f2a-11e9-9bfc-bc24b93ffdf9.PNG" alt="IMG_5254" title="" width="240" height="auto" /> <img src="https://user-images.githubusercontent.com/484309/54964744-d60e6880-4f2a-11e9-837e-80f51eedc442.png" alt="image" title="" width="240" height="auto" />

The first one's an iPhone SE, but even at iPhone X sizes (via FF's "responsive view" thingy) it's pretty weak. 

This thing's a "jQuery UI" widget, and I had a bit of a time tracking it down. It [looks like it's here](https://github.com/dreamwidth/dw-free/blob/develop/htdocs/js/jquery.iconselector.js), but it's not obvious to me how to fix the problem; it's probably pulling in some kind of generic jQuery UI default styling or something.

Here's how I ended up fixing it in my journal. Unlike that thing with the quick-reply (which at least was proportional to the constraints of the situation), I think this solution is pretty hacky and awful, partly because some of that dialog's properties just seem to come from Mars. IDK. Interested to hear what others think. 

```css
/* The UI styles don't do any resets or anything, so they get whomped
   by an innocent style-level default for list item formatting. */ 
#iconselector_icons_list {
   margin: 0;
   padding: 0;
}

@media only screen and (max-width: 45em) {
    .iconselector {
        font-size: .8em;
        left: 4vw !important;
        width: 90vw !important;
    }
    .iconselector .ui-dialog-titlebar {
        padding-top: 0;
        padding-bottom: 0;
    }
    .iconselector .ui-dialog-content {
        min-height: 360px !important;
        padding-bottom: 0;
    }
    .iconselector_top {
        margin-bottom: 0;
    }
    .iconselector_top .keywords {
        display: block;
    }
    .iconselector .kwmenu label:first-child {
        /* yes on screenreaders, no on display */
        border: 0;
        clip: rect(0 0 0 0);
        height: 1px;
        margin: -1px;
        overflow: hidden;
        padding: 0;
        position: absolute;
        white-space: nowrap;
        width: 1px;
    }
    .iconselector .kwmenu .keyword {
        display: block;
        white-space: nowrap;
        overflow-x: hidden;
    }
    #iconselector_select {
        float: none;
        margin-top: .2em;
        display: block;
    }
    #iconselector_icons {
        min-height: 160px;
        max-height: 100%;
    }
}
```

<img src="https://user-images.githubusercontent.com/484309/60132532-8b320600-9750-11e9-90fe-f738ed606f46.jpeg" width="320">
